"""Tests for the first-run wizard — Batch P3-G."""
from __future__ import annotations

import io
import json
import os
import sys
from contextlib import redirect_stdout
from pathlib import Path
from typing import Iterator, List

import pytest

from gitpilot import flags, init_wizard
from gitpilot.init_wizard import (
    FLAG_INIT_WIZARD,
    ScriptedPrompter,
    SUPPORTED_PROVIDERS,
    STARTER_MODES,
    WizardAnswers,
    WizardError,
    WizardResult,
    render_env,
    render_modes,
    run_wizard,
    starter_mode_slugs,
    supported_provider_slugs,
)
from gitpilot.trusted_folders import TrustStatus, TrustStore


@pytest.fixture(autouse=True)
def _isolate_flags() -> Iterator[None]:
    flags.clear_all_overrides()
    flags.set_override(FLAG_INIT_WIZARD, True)
    yield
    flags.clear_all_overrides()


@pytest.fixture()
def workspace(tmp_path: Path) -> Path:
    return tmp_path


@pytest.fixture()
def trust_store(tmp_path_factory: pytest.TempPathFactory) -> TrustStore:
    return TrustStore.load(tmp_path_factory.mktemp("trust") / "trusted.json")


# ----------------------------------------------------------------------
# Catalog smoke
# ----------------------------------------------------------------------

def test_provider_slugs_match_catalog() -> None:
    assert "anthropic" in supported_provider_slugs()
    assert "openai" in supported_provider_slugs()
    assert "ollama" in supported_provider_slugs()


def test_starter_mode_slugs() -> None:
    assert set(starter_mode_slugs()) == {"coder", "planner", "reviewer"}


# ----------------------------------------------------------------------
# Render snapshots
# ----------------------------------------------------------------------

def test_env_snapshot_for_anthropic() -> None:
    text = render_env(WizardAnswers(provider="anthropic", api_key="sk-test"))
    assert text == (
        "# GitPilot environment — generated by `gitpilot init --wizard`.\n"
        "# Only the keys you actually need are listed; add more as required.\n"
        "GITPILOT_LLM_PROVIDER=anthropic\n"
        "GITPILOT_DEFAULT_MODEL=claude-sonnet-4-5\n"
        "ANTHROPIC_API_KEY=sk-test\n"
    )


def test_env_snapshot_for_ollama_has_no_key() -> None:
    text = render_env(WizardAnswers(provider="ollama"))
    assert "GITPILOT_LLM_PROVIDER=ollama" in text
    assert "API_KEY" not in text


def test_modes_snapshot_for_coder() -> None:
    text = render_modes(WizardAnswers(mode_slug="coder"))
    assert text.startswith("# GitPilot modes")
    assert "slug: coder" in text
    assert "- read" in text and "- edit" in text and "- command" in text


def test_modes_snapshot_for_planner_is_read_only() -> None:
    text = render_modes(WizardAnswers(mode_slug="planner"))
    assert "- read" in text
    assert "- edit" not in text and "- command" not in text


def test_render_rejects_unknown_provider() -> None:
    with pytest.raises(WizardError):
        render_env(WizardAnswers(provider="not-a-provider", api_key="x"))


def test_render_rejects_unknown_mode() -> None:
    with pytest.raises(WizardError):
        render_modes(WizardAnswers(mode_slug="not-a-mode"))


def test_render_rejects_control_chars_in_key() -> None:
    with pytest.raises(WizardError):
        render_env(WizardAnswers(provider="anthropic", api_key="sk\nBAD"))


# ----------------------------------------------------------------------
# Non-interactive happy paths
# ----------------------------------------------------------------------

def test_full_run_writes_three_artefacts(
    workspace: Path, trust_store: TrustStore
) -> None:
    result = run_wizard(
        workspace,
        presets=WizardAnswers(
            provider="anthropic", api_key="sk-snapshot",
            mode_slug="coder", workspace_trust=True,
        ),
        trust_store=trust_store,
    )
    assert result.aborted is False
    written = {p.name for p in result.files_written}
    assert {".env", "modes.yaml", "AGENTS.md"} <= written
    assert result.trust_recorded is True
    # Trust store is persisted and reports the right status.
    assert trust_store.status(workspace) is TrustStatus.TRUSTED


def test_env_file_has_600_permissions(
    workspace: Path, trust_store: TrustStore
) -> None:
    if os.name != "posix":
        pytest.skip("POSIX-only mode bits")
    run_wizard(
        workspace,
        presets=WizardAnswers(provider="anthropic", api_key="sk-x", mode_slug="coder"),
        trust_store=trust_store,
    )
    mode = (workspace / ".env").stat().st_mode & 0o777
    assert mode == 0o600


def test_re_run_skips_existing_files_by_default(
    workspace: Path, trust_store: TrustStore
) -> None:
    presets = WizardAnswers(provider="ollama", mode_slug="coder")
    first = run_wizard(workspace, presets=presets, trust_store=trust_store)
    second = run_wizard(workspace, presets=presets, trust_store=trust_store)
    # Second run produces zero new files; everything is skipped.
    assert second.files_written == []
    assert {p.name for p, _ in second.files_skipped} >= {".env", "modes.yaml"}
    assert first.files_written  # sanity: first run actually wrote files


def test_overwrite_flag_replaces_env(
    workspace: Path, trust_store: TrustStore
) -> None:
    base = WizardAnswers(provider="ollama", mode_slug="coder")
    run_wizard(workspace, presets=base, trust_store=trust_store)
    # Manually mutate .env, then re-run with overwrite_env=True.
    (workspace / ".env").write_text("# tampered\n")
    base.overwrite_env = True
    base.overwrite_modes = True
    result = run_wizard(workspace, presets=base, trust_store=trust_store)
    new_env = (workspace / ".env").read_text(encoding="utf-8")
    assert "GITPILOT_LLM_PROVIDER=ollama" in new_env
    assert "# tampered" not in new_env
    assert (workspace / ".env") in result.files_written


# ----------------------------------------------------------------------
# Idempotency / determinism
# ----------------------------------------------------------------------

def test_identical_inputs_produce_byte_identical_output(
    workspace: Path, tmp_path_factory: pytest.TempPathFactory
) -> None:
    answers = WizardAnswers(provider="anthropic", api_key="sk-determ",
                            mode_slug="planner")
    a = render_env(answers)
    b = render_env(answers)
    assert a == b
    assert render_modes(answers) == render_modes(answers)


# ----------------------------------------------------------------------
# Validation
# ----------------------------------------------------------------------

def test_missing_api_key_for_hosted_provider_aborts_cleanly(
    workspace: Path, trust_store: TrustStore
) -> None:
    presets = WizardAnswers(provider="openai", api_key=None, mode_slug="coder")
    # The presets are *not complete* (key missing), so the wizard would
    # try to prompt.  Without a TTY-backed prompter the scripted one
    # below provides empty answers; the validation rejects the empty key.
    scripted = ScriptedPrompter(answers=["OpenAI", "", "Coder — Use to implement features and fix bugs.", True])
    with pytest.raises(WizardError):
        run_wizard(workspace, presets=presets, prompter=scripted,
                   trust_store=trust_store)
    # No files written.
    assert not (workspace / ".env").exists()
    assert not (workspace / ".gitpilot").exists()


def test_unknown_provider_in_preset_aborts_cleanly(
    workspace: Path, trust_store: TrustStore
) -> None:
    """A bad preset must be caught before any file is written."""
    presets = WizardAnswers(provider="not-a-provider", api_key="sk-x", mode_slug="coder")
    result = run_wizard(
        workspace,
        presets=presets,
        prompter=ScriptedPrompter(answers=[]),
        trust_store=trust_store,
    )
    # The full-preset path validates in _render_env → wraps in result.aborted.
    assert result.aborted is True
    # No partial state.
    assert not (workspace / ".env").exists()


# ----------------------------------------------------------------------
# Flag gating
# ----------------------------------------------------------------------

def test_flag_off_refuses_to_run(workspace: Path, trust_store: TrustStore) -> None:
    flags.set_override(FLAG_INIT_WIZARD, False)
    with pytest.raises(WizardError):
        run_wizard(
            workspace,
            presets=WizardAnswers(provider="ollama", mode_slug="coder"),
            trust_store=trust_store,
        )
    assert not (workspace / ".env").exists()


# ----------------------------------------------------------------------
# Atomicity — abort midway leaves no partial state
# ----------------------------------------------------------------------

def test_failure_during_modes_write_rolls_back_env(
    workspace: Path, trust_store: TrustStore, monkeypatch: pytest.MonkeyPatch
) -> None:
    """If writing modes.yaml fails after .env is written, the .env write
    must be rolled back so a retry sees a clean workspace."""
    real_replace = os.replace
    call_count = {"n": 0}

    def flaky_replace(src, dst):
        # Let the .env replace succeed; fail the next replace (modes.yaml).
        call_count["n"] += 1
        if call_count["n"] == 2:
            raise OSError("simulated disk-full")
        return real_replace(src, dst)

    monkeypatch.setattr(os, "replace", flaky_replace)

    result = run_wizard(
        workspace,
        presets=WizardAnswers(provider="ollama", mode_slug="coder"),
        trust_store=trust_store,
    )
    assert result.aborted is True
    # The earlier .env write was rolled back.
    assert not (workspace / ".env").exists()
    assert result.files_written == []


def test_keyboard_interrupt_before_writes_leaves_nothing(
    workspace: Path, trust_store: TrustStore
) -> None:
    class _Cancelling(ScriptedPrompter):
        def select(self, message, options, *, default=0):
            raise KeyboardInterrupt

    prompter = _Cancelling(answers=[])
    result = run_wizard(
        workspace,
        presets=None,
        prompter=prompter,
        trust_store=trust_store,
    )
    assert result.aborted is True
    assert result.reason == "user aborted"
    assert not (workspace / ".env").exists()
    assert not (workspace / ".gitpilot").exists()


# ----------------------------------------------------------------------
# Secret-safety — never echo the API key
# ----------------------------------------------------------------------

def test_scripted_prompter_does_not_echo_secret(
    workspace: Path, trust_store: TrustStore, capsys: pytest.CaptureFixture[str]
) -> None:
    scripted = ScriptedPrompter(answers=[
        "Anthropic Claude",     # provider
        "sk-secret-xyz-12345",  # api key
        "Coder — Use to implement features and fix bugs.",
        True,                   # trust
    ])
    run_wizard(workspace, presets=None, prompter=scripted, trust_store=trust_store)
    # The scripted prompter records every echo.  None of them must
    # contain the secret.
    for line in scripted.echoed:
        assert "sk-secret-xyz-12345" not in line
    # Likewise, nothing printed to capsys (the wizard itself uses prompter.echo).
    captured = capsys.readouterr()
    assert "sk-secret-xyz-12345" not in (captured.out + captured.err)


# ----------------------------------------------------------------------
# Interactive happy path (via ScriptedPrompter)
# ----------------------------------------------------------------------

def test_interactive_flow_writes_files(
    workspace: Path, trust_store: TrustStore
) -> None:
    scripted = ScriptedPrompter(answers=[
        "OpenAI",
        "sk-openai-test",
        "Reviewer — Use after a change is ready, before commit.",
        True,
    ])
    result = run_wizard(workspace, presets=None, prompter=scripted,
                        trust_store=trust_store)
    assert result.aborted is False
    assert result.provider == "openai"
    assert result.mode_slug == "reviewer"
    env_text = (workspace / ".env").read_text(encoding="utf-8")
    assert "GITPILOT_LLM_PROVIDER=openai" in env_text
    assert "OPENAI_API_KEY=sk-openai-test" in env_text
    modes_text = (workspace / ".gitpilot" / "modes.yaml").read_text(encoding="utf-8")
    assert "slug: reviewer" in modes_text


# ----------------------------------------------------------------------
# WizardResult serialisation
# ----------------------------------------------------------------------

def test_result_to_dict_is_serialisable(
    workspace: Path, trust_store: TrustStore
) -> None:
    result = run_wizard(
        workspace,
        presets=WizardAnswers(provider="ollama", mode_slug="coder"),
        trust_store=trust_store,
    )
    payload = json.dumps(result.to_dict())
    assert "files_written" in payload
